version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: echodb
      POSTGRES_USER: echouser
      POSTGRES_PASSWORD: echopass
    ports:
      - "5432:5432"